language: cpp
script:
- cmake .
- make
- make test
- make package
deploy:
  provider: bintray
  file: "descriptor.json"
  user:
    secure: "Z0jK72iacpKUD1r6zSWrp3h5aatHg+DulBxSAq8Is4bM35kA+Kfn8IsUWXoLlH/qgFLHXZ/Xb6turUtbeakDF1TyEtoZ0GzilRUxPfBTB1ERQYbEnNk0fMZTJXskOSBnFErhnxt+8zITepouVSt4LIGXnC9I/BsBqkTABWxEvucXIIlXLL6+750VxsnefpqfWwcRxS555tza8tDsUIPNWabl44pGPTkgCj48XaR7vrHWKE5CnO/iORe37dbwyGEIIsg00tHOR6ZHkoStOLAAId4ODkTZAm+m73m6A/ccp6KBqpD9gROCm9UDvqo9NmD90SzSBJxgf+ciRWVsAuo//WRR6bH8d9qQC/S3RIr6nhYed5NBZS8JOfZXXMLGUcUIzYzaH1JWmQgzQQ77T4Q7HzQ0GYONKSHZmHz8o551Y6f9DO2rJ8oidpYb6IuNqPft6HxcECKps8cfyCchxjoaX0w/ZoLM/2WcV1BuKd/gMGL8Ja/kagbmuSrpCD0q21th7EQ6g1FU+1IU8BDPaws6e7SyGnjBMsEOlBFz2AT+U9ENidcNXlkY25rr81qTJcvIRH56RyKcYiooEBeP06Pu6HNq6saDSDOnu1ylRVfv3EZ8aXiXhW8UpNRfjQexKiKelB6yjVZxEqp6QzDfG2pg6thMst6QA+J2olFG0vRPPS0="
  key:
    secure: "S0G6Syc4Jq7w/KuHrJ74ebshjGFy12jipSp0KL5GIBMajcDKFv/avE3zHCRdQgCtB/qAdGf9FeM4fj4eoAUIo/Hr/wU/Zs8Jad0CwENIF/q6wKFyLVfeimA8fZwL+iN7P9D4quZrBOKpsDukRt23enVy5AP7egl+8uoOC35irbTOKbbyi6WuOUr7aUHh1OUDC/W3RFzSmfvjn8m8RiCIQfu2APb4wPzRv7joJ1/iJTUoI5uNC6RbQBTibGJhwhn3MFWwhEaGjAaggf3deR9wutelZhgRdLTTdM9djftv5i6ThHKqcFTdGcQ6Ovn2BCi73yO3At4i03PSZoT2+2mmPI+kcpF5EDpZRFgXHuTP9UqhEyjcJmVpqpos+MASM8quaycwdXqEkRa9W4mJHcneu8YoctiXtouq0cF2FMS7I3wrGGiMokcuaHStbOk0nbYXbvhJbOeonXYDWLjwBF69fVQRDc4bbokQcquwXHeGj67WNRUZZPIQVu858Odm6xDO4xUx0D6hmuYCD6Rb9lIc7CGr7mqsfs48JddZI5wFirGCEeOWgEMZ6UWpUSbJtSjIC6IwAkipt1IcwE5LoMx+2OBoK6lXLzGKI/DiVEBCd8lfUUDlBn2P0TKtsdn1geVPz4Y+WOlOXiySJJoRGP+dZPoHeOb8iDRiVPow363mtrU="