language: cpp
script:
- cmake .
- make
- make test
- make package
deploy:
  provider: bintray
  file: descriptor.json
  user:
    secure: Z0jK72iacpKUD1r6zSWrp3h5aatHg+DulBxSAq8Is4bM35kA+Kfn8IsUWXoLlH/qgFLHXZ/Xb6turUtbeakDF1TyEtoZ0GzilRUxPfBTB1ERQYbEnNk0fMZTJXskOSBnFErhnxt+8zITepouVSt4LIGXnC9I/BsBqkTABWxEvucXIIlXLL6+750VxsnefpqfWwcRxS555tza8tDsUIPNWabl44pGPTkgCj48XaR7vrHWKE5CnO/iORe37dbwyGEIIsg00tHOR6ZHkoStOLAAId4ODkTZAm+m73m6A/ccp6KBqpD9gROCm9UDvqo9NmD90SzSBJxgf+ciRWVsAuo//WRR6bH8d9qQC/S3RIr6nhYed5NBZS8JOfZXXMLGUcUIzYzaH1JWmQgzQQ77T4Q7HzQ0GYONKSHZmHz8o551Y6f9DO2rJ8oidpYb6IuNqPft6HxcECKps8cfyCchxjoaX0w/ZoLM/2WcV1BuKd/gMGL8Ja/kagbmuSrpCD0q21th7EQ6g1FU+1IU8BDPaws6e7SyGnjBMsEOlBFz2AT+U9ENidcNXlkY25rr81qTJcvIRH56RyKcYiooEBeP06Pu6HNq6saDSDOnu1ylRVfv3EZ8aXiXhW8UpNRfjQexKiKelB6yjVZxEqp6QzDfG2pg6thMst6QA+J2olFG0vRPPS0=
  key:
    secure: TRNmJYaS5CB7YJ30i+AprrqOPzAgTpnVwvcKUevUgbVzU3KFhwRXaL9omOj0IhsSP636U65fsMETFP/l+qCvIdyFeCbPgzY2hLL0/QRSYzGRLWv8+V4H13aEePQzYerZYxw2hCeksvWiRoTI2gNKN9WWbuzc0yaC1NDnb/1unQAnmeBrMNsFE+5uEDSLar2jAhU6kAQt1xzYUC5/Lwbs5hEStYdvh9uFRFxw5Nds3ZX8yp2WTv6S8gT2D4/zUGyvW31X5SQAd04AF+G0VByZTlCSxKgd24a1TfP8etNAZ8jsO+glYLlaoHydeMbETiE5kbQXsIpC8s+3dD6AsvmBiJtMimxDu/m+R3piQu2sKWLLHNAwAqBN9FhHbKI/tz7YQwJ33tsmmiIm6P8Nj3IDIOdBTHJ1jZIfqqk2MGHR76p6ZHqlz3e9AHnD3KPJOrh1MspWyVsvSeMKi8FtXOiv9RKiyqLRU17gx045HqQpTKchZc/LCzSEX4H3myfedCfRutOYOV370MXszH77ZC445XIFUbgHdC8AsN+XwTgg10rrKriZQcup66NmLrS9RLIJAmdN+7rUNWzg7IVcnaf3S/bGE7A7y/wpHjQPZZ8EuGZWBbLryFNLCrhKZltpa+ZbBbDxF62Dri+cqjxEPl1b+MME8y6Bd4cf02e//Fua5N0=
  skip_cleanup: true