language: cpp
script:
- cmake .
- make
- make test
- make package
deploy:
  provider: bintray
  file: descriptor.json
  user:
    secure: i7I6bs8Hje1huAHX4MU3gO/N6KWUg44sTOOc6mxDJ/ULwaFVFt5pWTgRtKTWDDGn6UbTuYX6KQupZj5p6VgJ4UAt72Mk8aWXmvnnbAH/j3nXBJA+3NJ4WWGYURrq+/YcMvG4FA8G72E7bEzXTL53DZfLxVIi+kD3dr7HBIPQYt3hSf77KlJ2/pFQkbcBTI6kl1IE3N8MjnngrvkOlG3etSfS4rhdByi8zyXz8oyZPahcnRjaZDvUnZrddGxH6CTSQC7MV1EMC08xt9oqJRojCcKZU5RwMm8C/qjNB+mlhG9rGQZoInLnxFFUJ3061U09T30q0kkVDk0D27EkvlBnZ61yk2PHshrg1/h1kvEYp6HRCMBhlslKoxuAyYna+sy+bNQ6O6ccVqLakk8plnDQraGCBSkqZs+NND5fFLF6fjChqcq5sX5/k6tx7KgH6UeFD8v5SCT1488av0rNO5psuqbIPm0HH56ziPDq9TdHYFw2SpY/0ifXoI2SOFFxDtnjG+FuFnX8XvIhW4+8bBLNylNuOwSEErXGbKMyCxZ+4fZ7l6JQpiU/eDgWVXduaf1pUc1o7S2RfIdX8W3PHGmc6BJqNhTiqkcOURxtMd6+ilbPlplmGdsUTRuX9+hH1ucawyPid7A01DQgcNbtLgiV+tMdY8CIS4BcmM1ZfviMCwA=
  key:
    secure: TRNmJYaS5CB7YJ30i+AprrqOPzAgTpnVwvcKUevUgbVzU3KFhwRXaL9omOj0IhsSP636U65fsMETFP/l+qCvIdyFeCbPgzY2hLL0/QRSYzGRLWv8+V4H13aEePQzYerZYxw2hCeksvWiRoTI2gNKN9WWbuzc0yaC1NDnb/1unQAnmeBrMNsFE+5uEDSLar2jAhU6kAQt1xzYUC5/Lwbs5hEStYdvh9uFRFxw5Nds3ZX8yp2WTv6S8gT2D4/zUGyvW31X5SQAd04AF+G0VByZTlCSxKgd24a1TfP8etNAZ8jsO+glYLlaoHydeMbETiE5kbQXsIpC8s+3dD6AsvmBiJtMimxDu/m+R3piQu2sKWLLHNAwAqBN9FhHbKI/tz7YQwJ33tsmmiIm6P8Nj3IDIOdBTHJ1jZIfqqk2MGHR76p6ZHqlz3e9AHnD3KPJOrh1MspWyVsvSeMKi8FtXOiv9RKiyqLRU17gx045HqQpTKchZc/LCzSEX4H3myfedCfRutOYOV370MXszH77ZC445XIFUbgHdC8AsN+XwTgg10rrKriZQcup66NmLrS9RLIJAmdN+7rUNWzg7IVcnaf3S/bGE7A7y/wpHjQPZZ8EuGZWBbLryFNLCrhKZltpa+ZbBbDxF62Dri+cqjxEPl1b+MME8y6Bd4cf02e//Fua5N0=
  skip_cleanup: true